name: Base Setup
description: Checkout code, Setup NodeJS and Install Dependencies
runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20.19.0
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile